language: cpp
dist: trusty
sudo: false
matrix:
    include:
        -   os: linux
            compiler: gcc
            addons: &gcc6
                apt:
                    sources: ['ubuntu-toolchain-r-test']
                    packages:
                        - 'g++-7'
                        - 'libsdl2-dev'
                        - 'libglew-dev'
            env: C_COMPILER='gcc-7' CXX_COMPILER='g++-7'
        -   os: linux
            compiler: clang
            addons: &clang40
                apt:
                    sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
                    packages:
                        - 'libstdc++-7-dev'
                        - 'clang-5.0'
                        - 'libsdl2-dev'
                        - 'libglew-dev'
            env: C_COMPILER='clang-5.0' CXX_COMPILER='clang++-5.0'
before_script:
    - export CC=${C_COMPILER}
    - export CXX=${CXX_COMPILER}
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -Wdev ..
    - cmake --build .
    - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x16 +extension RANDR"
    - sleep 3
script:
    - cd ${TRAVIS_BUILD_DIR}/build
    - env DISPLAY=:99.0 ./glwrapper-test
notifications:
    email:
        on_success: change
        on_failure: change
